// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Service.Iletisim.Data;

#nullable disable

namespace Service.Iletisim.Migrations
{
    [DbContext(typeof(IletisimContext))]
    [Migration("20230614064146_IletisimEntitySeedDataEklendi")]
    partial class IletisimEntitySeedDataEklendi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Service.Iletisim.Entities.Iletisim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("IletisimType")
                        .HasColumnType("integer");

                    b.Property<Guid>("KisiId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Iletisim");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d27306b2-1c2e-47f9-96ef-ec91b02e83bf"),
                            Icerik = "05383941232",
                            IletisimType = 1,
                            KisiId = new Guid("856b39fb-d802-4574-a0b4-872a12589c59")
                        },
                        new
                        {
                            Id = new Guid("bd999251-da45-418d-8604-1f69d552fc3f"),
                            Icerik = "abc@abc.com",
                            IletisimType = 2,
                            KisiId = new Guid("856b39fb-d802-4574-a0b4-872a12589c59")
                        },
                        new
                        {
                            Id = new Guid("9de5438f-4237-4ec5-b081-d54ed8cb64e7"),
                            Icerik = "Ankara",
                            IletisimType = 3,
                            KisiId = new Guid("856b39fb-d802-4574-a0b4-872a12589c59")
                        },
                        new
                        {
                            Id = new Guid("e51d2709-dcc1-4016-8c0c-9936177c1e67"),
                            Icerik = "Ankara",
                            IletisimType = 3,
                            KisiId = new Guid("927f71b9-fef6-44ce-b6d8-a8ee86df89e0")
                        },
                        new
                        {
                            Id = new Guid("09a87d0c-7cc6-4ddd-affd-34699cc1547f"),
                            Icerik = "05383946677",
                            IletisimType = 1,
                            KisiId = new Guid("927f71b9-fef6-44ce-b6d8-a8ee86df89e0")
                        },
                        new
                        {
                            Id = new Guid("7cfac4e8-a901-4627-9c24-f409c86a30b1"),
                            Icerik = "05383948899",
                            IletisimType = 1,
                            KisiId = new Guid("927f71b9-fef6-44ce-b6d8-a8ee86df89e0")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
