// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Service.Kisi.Data;

#nullable disable

namespace Service.Rapor.Migrations
{
    [DbContext(typeof(RaporContext))]
    [Migration("20230614103701_RaporRaporBilgiEntityOlusturma")]
    partial class RaporRaporBilgiEntityOlusturma
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Service.Rapor.Entities.Rapor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("TalepEdildigiTarih")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Rapor");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d6245fe2-0947-11ee-b208-54e1ad72c6a1"),
                            Durum = 2,
                            TalepEdildigiTarih = new DateTimeOffset(new DateTime(2023, 6, 14, 13, 37, 1, 329, DateTimeKind.Unspecified).AddTicks(461), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("e50ef18e-0947-11ee-b20b-54e1ad72c6a1"),
                            Durum = 2,
                            TalepEdildigiTarih = new DateTimeOffset(new DateTime(2023, 6, 14, 13, 37, 1, 329, DateTimeKind.Unspecified).AddTicks(502), new TimeSpan(0, 3, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Service.Rapor.Entities.RaporBilgi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("KisiSayisi")
                        .HasColumnType("integer");

                    b.Property<string>("KonumBilgisi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("RaporId")
                        .HasColumnType("uuid");

                    b.Property<int>("TelefonNumarasiSayisi")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RaporId");

                    b.ToTable("RaporBilgi");

                    b.HasData(
                        new
                        {
                            Id = new Guid("07f4b594-0948-11ee-b20c-54e1ad72c6a1"),
                            KisiSayisi = 2,
                            KonumBilgisi = "Ankara",
                            RaporId = new Guid("d6245fe2-0947-11ee-b208-54e1ad72c6a1"),
                            TelefonNumarasiSayisi = 3
                        },
                        new
                        {
                            Id = new Guid("7ea050d6-0948-11ee-b20d-54e1ad72c6a1"),
                            KisiSayisi = 0,
                            KonumBilgisi = "Mersin",
                            RaporId = new Guid("e50ef18e-0947-11ee-b20b-54e1ad72c6a1"),
                            TelefonNumarasiSayisi = 0
                        });
                });

            modelBuilder.Entity("Service.Rapor.Entities.RaporBilgi", b =>
                {
                    b.HasOne("Service.Rapor.Entities.Rapor", "Rapor")
                        .WithMany("RaporBilgileri")
                        .HasForeignKey("RaporId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rapor");
                });

            modelBuilder.Entity("Service.Rapor.Entities.Rapor", b =>
                {
                    b.Navigation("RaporBilgileri");
                });
#pragma warning restore 612, 618
        }
    }
}
