// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Service.Kisi.Data;

#nullable disable

namespace Service.Kisi.Migrations
{
    [DbContext(typeof(KisiContext))]
    partial class KisiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Service.Kisi.Entities.Kisi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Firma")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Kisi");

                    b.HasData(
                        new
                        {
                            Id = new Guid("856b39fb-d802-4574-a0b4-872a12589c59"),
                            Ad = "John",
                            Firma = "ABC Corporation",
                            Soyad = "Doe"
                        },
                        new
                        {
                            Id = new Guid("927f71b9-fef6-44ce-b6d8-a8ee86df89e0"),
                            Ad = "Jane",
                            Firma = " XYZ Ltd.",
                            Soyad = "Smith"
                        },
                        new
                        {
                            Id = new Guid("a5ce0ec5-1c1a-4a15-86f9-cdde439a92a2"),
                            Ad = "Michael",
                            Firma = "QWERTY Holdings",
                            Soyad = "Johnson"
                        },
                        new
                        {
                            Id = new Guid("e0207c71-f788-4067-8ebf-3a48e7b6966e"),
                            Ad = "Emily",
                            Firma = "XYZ Ltd.",
                            Soyad = "Brown"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
